CREATE TABLE equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL,
    tipo VARCHAR NOT NULL,
    marca VARCHAR NOT NULL,
    problema_relatado TEXT NOT NULL,
    status VARCHAR DEFAULT 'Em análise'
);